# Problem Statement

For the next set of questions, we will be using census data from the United States in the United States. This dataset contains population data for countries and states in the US from 2010 to 2015. 

1. Which state has the most countries in it? (hint: consider the sumlevel key carefully! You'll need this for future questions too...)
2. Only looking at the three most populous countries for each state, what are the three most populous states (in order of highest population to lowest population)? Use CENSUS2010POP
3. Which city has the most countries in it?
4. Which region has the most division in it?

In [3]:
import numpy as np
import pandas as pd

import matplotlib.pyplot as plt
import seaborn as sns

In [4]:
# read and import file
df = pd.read_csv(r"C:\Users\Ogundele Yakub\Desktop\DA Projects\DAFI Project\Python Projects\census.csv")
df

,SUMLEV,REGION,DIVISION,STATE,COUNTY,STNAME,CTYNAME,CENSUS2010POP,ESTIMATESBASE2010,POPESTIMATE2010,...,RDOMESTICMIG2011,RDOMESTICMIG2012,RDOMESTICMIG2013,RDOMESTICMIG2014,RDOMESTICMIG2015,RNETMIG2011,RNETMIG2012,RNETMIG2013,RNETMIG2014,RNETMIG2015
0,40,3,6,1,0,Alabama,Alabama,4779736,4780127,4785161,...,0.002295,-0.193196,0.381066,0.582002,-0.467369,1.030015,0.826644,1.383282,1.724718,0.712594
1,50,3,6,1,1,Alabama,Autauga County,54571,54571,54660,...,7.242091,-2.915927,-3.012349,2.265971,-2.530799,7.606016,-2.626146,-2.722002,2.592270,-2.187333
2,50,3,6,1,3,Alabama,Baldwin County,182265,182265,183193,...,14.832960,17.647293,21.845705,19.243287,17.197872,15.844176,18.559627,22.727626,20.317142,18.293499
3,50,3,6,1,5,Alabama,Barbour County,27457,27457,27341,...,-4.728132,-2.500690,-7.056824,-3.904217,-10.543299,-4.874741,-2.758113,-7.167664,-3.978583,-10.543299
4,50,3,6,1,7,Alabama,Bibb County,22915,22919,22861,...,-5.527043,-5.068871,-6.201001,-0.177537,0.177258,-5.088389,-4.363636,-5.403729,0.754533,1.107861
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3188,50,4,8,56,37,Wyoming,Sweetwater County,43806,43806,43593,...,1.072643,16.243199,-5.339774,-14.252889,-14.248864,1.255221,16.243199,-5.295460,-14.075283,-14.070195
3189,50,4,8,56,39,Wyoming,Teton County,21294,21294,21297,...,-1.589565,0.972695,19.525929,14.143021,-0.564849,0.654527,2.408578,21.160658,16.308671,1.520747
3190,50,4,8,56,41,Wyoming,Uinta County,21118,21118,21102,...,-17.755986,-4.916350,-6.902954,-14.215862,-12.127022,-18.136812,-5.536861,-7.521840,-14.740608,-12.606351
3191,50,4,8,56,43,Wyoming,Washakie County,8533,8533,8545,...,-11.637475,-0.827815,-2.013502,-17.781491,1.682288,-11.990126,-1.182592,-2.250385,-18.020168,1.441961
3192,50,4,8,56,45,Wyoming,Weston County,7208,7208,7181,...,-11.752361,-8.040059,12.372583,1.533635,6.935294,-12.032179,-8.040059,12.372583,1.533635,6.935294

# Data Inspection

In [5]:
# shape of the data
df.shape

(3193, 100)

In [6]:
# info of the data
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3193 entries, 0 to 3192
Data columns (total 100 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   SUMLEV                 3193 non-null   int64
 1   REGION                 3193 non-null   int64
 2   DIVISION               3193 non-null   int64
 3   STATE                  3193 non-null   int64
 4   COUNTY                 3193 non-null   int64
 5   STNAME                 3193 non-null   object
 6   CTYNAME                3193 non-null   object
 7   CENSUS2010POP          3193 non-null   int64
 8   ESTIMATESBASE2010      3193 non-null   int64
 9   POPESTIMATE2010        3193 non-null   int64
 10  POPESTIMATE2011        3193 non-null   int64
 11  POPESTIMATE2012        3193 non-null   int64
 12  POPESTIMATE2013        3193 non-null   int64
 13  POPESTIMATE2014        3193 non-null   int64
 14  POPESTIMATE2015        3193 non-null   int64
 15  NPOPCHG_2010           3193 non-null   int64
 16  NPOPCHG_2011           3193 non-null   int64
 17  NPOPCHG_2012           3193 non-null   int64
 18  NPOPCHG_2013           3193 non-null   int64
 19  NPOPCHG_2014           3193 non-null   int64
 20  NPOPCHG_2015           3193 non-null   int64
 21  BIRTHS2010             3193 non-null   int64
 22  BIRTHS2011             3193 non-null   int64
 23  BIRTHS2012             3193 non-null   int64
 24  BIRTHS2013             3193 non-null   int64
 25  BIRTHS2014             3193 non-null   int64
 26  BIRTHS2015             3193 non-null   int64
 27  DEATHS2010             3193 non-null   int64
 28  DEATHS2011             3193 non-null   int64
 29  DEATHS2012             3193 non-null   int64
 30  DEATHS2013             3193 non-null   int64
 31  DEATHS2014             3193 non-null   int64
 32  DEATHS2015             3193 non-null   int64
 33  NATURALINC2010         3193 non-null   int64
 34  NATURALINC2011         3193 non-null   int64
 35  NATURALINC2012         3193 non-null   int64
 36  NATURALINC2013         3193 non-null   int64
 37  NATURALINC2014         3193 non-null   int64
 38  NATURALINC2015         3193 non-null   int64
 39  INTERNATIONALMIG2010   3193 non-null   int64
 40  INTERNATIONALMIG2011   3193 non-null   int64
 41  INTERNATIONALMIG2012   3193 non-null   int64
 42  INTERNATIONALMIG2013   3193 non-null   int64
 43  INTERNATIONALMIG2014   3193 non-null   int64
 44  INTERNATIONALMIG2015   3193 non-null   int64
 45  DOMESTICMIG2010        3193 non-null   int64
 46  DOMESTICMIG2011        3193 non-null   int64
 47  DOMESTICMIG2012        3193 non-null   int64
 48  DOMESTICMIG2013        3193 non-null   int64
 49  DOMESTICMIG2014        3193 non-null   int64
 50  DOMESTICMIG2015        3193 non-null   int64
 51  NETMIG2010             3193 non-null   int64
 52  NETMIG2011             3193 non-null   int64
 53  NETMIG2012             3193 non-null   int64
 54  NETMIG2013             3193 non-null   int64
 55  NETMIG2014             3193 non-null   int64
 56  NETMIG2015             3193 non-null   int64
 57  RESIDUAL2010           3193 non-null   int64
 58  RESIDUAL2011           3193 non-null   int64
 59  RESIDUAL2012           3193 non-null   int64
 60  RESIDUAL2013           3193 non-null   int64
 61  RESIDUAL2014           3193 non-null   int64
 62  RESIDUAL2015           3193 non-null   int64
 63  GQESTIMATESBASE2010    3193 non-null   int64
 64  GQESTIMATES2010        3193 non-null   int64
 65  GQESTIMATES2011        3193 non-null   int64
 66  GQESTIMATES2012        3193 non-null   int64
 67  GQESTIMATES2013        3193 non-null   int64
 68  GQESTIMATES2014        3193 non-null   int64
 69  GQESTIMATES2015        3193 non-null   int64
 70  RBIRTH2011             3193 non-null   float64
 71  RBIRTH2012             3193 non-null   float64
 72  RBIRTH2013             3193 non-null   float64
 73  RBIRTH2014             3193 non-null   float64
 74  RBIRTH2015             3193 non-null   float64
 75  RDEATH2011             3193 non-null   float64
 76  RDEATH2012             3193 non-null   float64
 77  RDEATH2013             3193 non-null   float64
 78  RDEATH2014             3193 non-null   float64
 79  RDEATH2015             3193 non-null   float64
 80  RNATURALINC2011        3193 non-null   float64
 81  RNATURALINC2012        3193 non-null   float64
 82  RNATURALINC2013        3193 non-null   float64
 83  RNATURALINC2014        3193 non-null   float64
 84  RNATURALINC2015        3193 non-null   float64
 85  RINTERNATIONALMIG2011  3193 non-null   float64
 86  RINTERNATIONALMIG2012  3193 non-null   float64
 87  RINTERNATIONALMIG2013  3193 non-null   float64
 88  RINTERNATIONALMIG2014  3193 non-null   float64
 89  RINTERNATIONALMIG2015  3193 non-null   float64
 90  RDOMESTICMIG2011       3193 non-null   float64
 91  RDOMESTICMIG2012       3193 non-null   float64
 92  RDOMESTICMIG2013       3193 non-null   float64
 93  RDOMESTICMIG2014       3193 non-null   float64
 94  RDOMESTICMIG2015       3193 non-null   float64
 95  RNETMIG2011            3193 non-null   float64
 96  RNETMIG2012            3193 non-null   float64
 97  RNETMIG2013            3193 non-null   float64
 98  RNETMIG2014            3193 non-null   float64
 99  RNETMIG2015            3193 non-null   float64
dtypes: float64(30), int64(68), object(2)
memory usage: 2.4+ MB

In [8]:
# columns of the data
df.columns.tolist()

['SUMLEV',
 'REGION',
 'DIVISION',
 'STATE',
 'COUNTY',
 'STNAME',
 'CTYNAME',
 'CENSUS2010POP',
 'ESTIMATESBASE2010',
 'POPESTIMATE2010',
 'POPESTIMATE2011',
 'POPESTIMATE2012',
 'POPESTIMATE2013',
 'POPESTIMATE2014',
 'POPESTIMATE2015',
 'NPOPCHG_2010',
 'NPOPCHG_2011',
 'NPOPCHG_2012',
 'NPOPCHG_2013',
 'NPOPCHG_2014',
 'NPOPCHG_2015',
 'BIRTHS2010',
 'BIRTHS2011',
 'BIRTHS2012',
 'BIRTHS2013',
 'BIRTHS2014',
 'BIRTHS2015',
 'DEATHS2010',
 'DEATHS2011',
 'DEATHS2012',
 'DEATHS2013',
 'DEATHS2014',
 'DEATHS2015',
 'NATURALINC2010',
 'NATURALINC2011',
 'NATURALINC2012',
 'NATURALINC2013',
 'NATURALINC2014',
 'NATURALINC2015',
 'INTERNATIONALMIG2010',
 'INTERNATIONALMIG2011',
 'INTERNATIONALMIG2012',
 'INTERNATIONALMIG2013',
 'INTERNATIONALMIG2014',
 'INTERNATIONALMIG2015',
 'DOMESTICMIG2010',
 'DOMESTICMIG2011',
 'DOMESTICMIG2012',
 'DOMESTICMIG2013',
 'DOMESTICMIG2014',
 'DOMESTICMIG2015',
 'NETMIG2010',
 'NETMIG2011',
 'NETMIG2012',
 'NETMIG2013',
 'NETMIG2014',
 'NETMIG2015',
 'RESIDUAL2010',
 'RESIDUAL2011',
 'RESIDUAL2012',
 'RESIDUAL2013',
 'RESIDUAL2014',
 'RESIDUAL2015',
 'GQESTIMATESBASE2010',
 'GQESTIMATES2010',
 'GQESTIMATES2011',
 'GQESTIMATES2012',
 'GQESTIMATES2013',
 'GQESTIMATES2014',
 'GQESTIMATES2015',
 'RBIRTH2011',
 'RBIRTH2012',
 'RBIRTH2013',
 'RBIRTH2014',
 'RBIRTH2015',
 'RDEATH2011',
 'RDEATH2012',
 'RDEATH2013',
 'RDEATH2014',
 'RDEATH2015',
 'RNATURALINC2011',
 'RNATURALINC2012',
 'RNATURALINC2013',
 'RNATURALINC2014',
 'RNATURALINC2015',
 'RINTERNATIONALMIG2011',
 'RINTERNATIONALMIG2012',
 'RINTERNATIONALMIG2013',
 'RINTERNATIONALMIG2014',
 'RINTERNATIONALMIG2015',
 'RDOMESTICMIG2011',
 'RDOMESTICMIG2012',
 'RDOMESTICMIG2013',
 'RDOMESTICMIG2014',
 'RDOMESTICMIG2015',
 'RNETMIG2011',
 'RNETMIG2012',
 'RNETMIG2013',
 'RNETMIG2014',
 'RNETMIG2015']

In [10]:
# check for missing values
df.isnull().sum()

SUMLEV         0
REGION         0
DIVISION       0
STATE          0
COUNTY         0
              ..
RNETMIG2011    0
RNETMIG2012    0
RNETMIG2013    0
RNETMIG2014    0
RNETMIG2015    0
Length: 100, dtype: int64

In [11]:
# summary statistucs of the data frame
df.describe().astype("int")

,SUMLEV,REGION,DIVISION,STATE,COUNTY,CENSUS2010POP,ESTIMATESBASE2010,POPESTIMATE2010,POPESTIMATE2011,POPESTIMATE2012,...,RDOMESTICMIG2011,RDOMESTICMIG2012,RDOMESTICMIG2013,RDOMESTICMIG2014,RDOMESTICMIG2015,RNETMIG2011,RNETMIG2012,RNETMIG2013,RNETMIG2014,RNETMIG2015
count,3193,3193,3193,3193,3193,3193,3193,3193,3193,3193,...,3193,3193,3193,3193,3193,3193,3193,3193,3193,3193
mean,49,2,5,30,101,193387,193396,193765,195251,196744,...,-1,-2,-1,-2,-1,0,-1,0,-1,0
std,1,0,1,15,107,1176201,1176244,1178710,1189647,1200508,...,10,11,12,11,12,10,12,12,11,12
min,40,1,1,1,0,82,82,83,90,81,...,-128,-147,-109,-178,-84,-128,-147,-102,-178,-62
25%,50,2,4,18,33,11299,11299,11275,11277,11195,...,-6,-7,-6,-7,-6,-5,-6,-5,-6,-5
50%,50,3,5,29,77,26424,26446,26467,26417,26362,...,-1,-2,-1,-1,-2,0,-1,0,0,0
75%,50,3,7,45,133,71404,71491,71721,72387,72496,...,2,2,3,3,3,4,3,4,4,5
max,50,4,9,56,840,37253956,37254503,37334079,37700034,38056055,...,101,119,239,146,281,101,119,239,146,281

#### 
Based on the provided data, we have information on various demographic and population statistics for different regions, divisions, states, and counties. The data includes population figures from the 2010 census, estimates base for 2010, and population estimates for the years 2010 to 2015. Additionally, it includes information on domestic migration (RDOMESTICMIG) and net migration (RNETMIG) for the corresponding years.

The statistics show that the average population count across all regions is around 49, with a standard deviation of 1. The census2010pop ranges from a minimum of 40 to a maximum of 840. The average estimated base population in 2010 is around 193,000, with a standard deviation of approximately 1.1 million.

The migration data indicates that the average domestic migration is close to zero, with a small standard deviation. The net migration data also shows a similar pattern.

In [13]:
# confirm data type
df.dtypes

SUMLEV           int64
REGION           int64
DIVISION         int64
STATE            int64
COUNTY           int64
                ...
RNETMIG2011    float64
RNETMIG2012    float64
RNETMIG2013    float64
RNETMIG2014    float64
RNETMIG2015    float64
Length: 100, dtype: object

In [47]:
# Top 5 states
# Assuming you have a DataFrame called 'df' with a column 'state' and 'street_name'
# Count the states
state_counts = df['STATE'].value_counts()
state_counts

# Group by state name and return the state names
grouped_states = df.groupby('STNAME').size().reset_index(name='count')
grouped_states

# Top 5 stATE
top_5_states = grouped_states.nlargest(5, 'count')
print(top_5_states)

      STNAME  count
43     Texas    255
10   Georgia    160
46  Virginia    134
17  Kentucky    121
25  Missouri    116

## Question 1
The state with the most county in it is Texas with state code number 43 and it has 255 county in it.
Georgia follow Texas with 160 county, Virginia is the third state with 134 county in it.  
Kentucky is the 4th state with 121 county.
Missouri is the 5th state with 116 county.

In [33]:
# Assuming 'df' is your DataFrame
df['CENSUS2010POP'] = pd.to_numeric(df['CENSUS2010POP'], errors='coerce')

# Group by county name and calculate the sum of CENSUS2010POP
county_sums = df.groupby('CTYNAME')['CENSUS2010POP'].sum()

# Group by state name and calculate the sum of CENSUS2010POP
state_sums = df.groupby('STNAME')['CENSUS2010POP'].sum()

# Return the top 5 county by population
top_5_county = county_sums.nlargest(3)
# Return the top 5 state by population
top_5_state = state_sums.nlargest(3)
print(top_5_county)
print(top_5_state)

CTYNAME
California    37253956
Texas         25145561
New York      19378102
Name: CENSUS2010POP, dtype: int64
STNAME
California    74507912
Texas         50291122
New York      38756204
Name: CENSUS2010POP, dtype: int64

## Question 2

The most populous county is California county with a population of over 37 million(37,253,956) follow by Texas county with population of over 25 million(25,145,561).
New York county is the third populous county with over 19 million(19,378.102).

The most populous state is California with a population of over 74 million(74,507,912) followed by Texas with a population of over 50 milllion and thirdly New York with total population of over 38 million people(38,756,204)

In [36]:
# Top 5 states
# Assuming you have a DataFrame called 'df' with a column 'state' and 'street_name'
# Count the states
state_counts = df['COUNTY'].value_counts()
state_counts

# Group by street name and return the street names
grouped_streets = df.groupby('CTYNAME').size().reset_index(name='count')
grouped_streets

# Top 5 street names
top_5_streets = grouped_streets.nlargest(5, 'count')
print(top_5_streets)

                CTYNAME  count
1822  Washington County     30
855    Jefferson County     25
609     Franklin County     24
849      Jackson County     23
1004     Lincoln County     23

## Question 3
The city with the most county is Washington with 30 county followed by Jefferson with 25 countys.
The thrid city with the most county Franklin with 24 countys and Jackson city is the fourth city with 23 countys.
Lincoln county has 23 countys in it.

In [42]:
# Distinct count of the 'DIVISION' column
distinct_division_count = df['DIVISION'].nunique()
grouped_streets = df.groupby('REGION').size().reset_index(name='count')
print(distinct_division_count)
print(grouped_streets)

9
   REGION  count
0       1    226
1       2   1067
2       3   1439
3       4    461

## Question 4
The region with the most division in it is region 3